a = input('Digite algo:')
print('O tipo primitivo desse valor é', type(a))
print('Só tem espaços?', a.isspace())
print('é um número?', a.isnumeric())
print('é alfabetico?', a.isalpha())
print('é apenas maiusculas?', a.isupper())
print('é apenas minusculas?', a.islower())
print('é alfanumerico?', a.isalnum())
print('esta capitalizada?', a.istitle)
